---
title: "Medical_data_specificity_tasks"
author: "NataliaLaskina"
date: "2024-11-02"
output: 
   html_document:
       toc: true
       toc_float:
           collapsed: false
           smooth_scroll: true
       theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstatix)
library(pROC)
library(readxl)
library(gtsummary)

```


```{r}

trauma_data <- read_excel('C:/Users/laskn/BioStat_2024/data/originals/trauma.xlsx')

trauma_data %>% summary()

```

```{r}

trauma_data <- trauma_data %>% 
    mutate(across(c(id, Sex, Death), ~ as.factor(.x)))

trauma_data$Height <- gsub('"', '', trauma_data$Height)

trauma_data$Height <- as.numeric(trauma_data$Height)

trauma_data %>% summary()

```

```{r}

trauma_data_cleaned <- trauma_data %>%

    mutate(
        
        # Заменим единицы в дюймах на единицы в метрах
        Height = round(Height * 0.0254, 1),
        # Преобразуйте Weight из фунтов в килограммы
        Weight = round(Weight * 0.453592, 1),
        
       # Заменим "0" на пропущенные значения
        Hb = na_if(Hb, 0),
        
        BMI = (Weight / Height / Height) %>% round(1) 
        
        )

trauma_data_cleaned %>% head()

trauma_data_cleaned %>% summary()

```

```{r}

trauma_data_cleaned <- trauma_data_cleaned %>%
  mutate(
    Hb_Low = case_when(
      Sex == "Male" & Hb < 13.5 ~ TRUE,
      Sex == "Female" & Hb < 12 ~ TRUE,
      TRUE ~ FALSE
    )
  )

# Считаем количество пациентов с низким Hb
n_low_hb <- sum(trauma_data_cleaned$Hb_Low, na.rm = TRUE)

percent_low_hb <- (n_low_hb / nrow(trauma_data_cleaned)) * 100

cat("У", n_low_hb, "пациентов (", round(percent_low_hb, 1), "%) был снижен уровень гемоглобина.\n")

```

```{r}

# Средний ИМТ
mean_bmi <- mean(trauma_data_cleaned$BMI, na.rm = TRUE)
sd_bmi <- sd(trauma_data_cleaned$BMI, na.rm = TRUE)

# Доля пациентов с ожирением
n_obese <- sum(trauma_data_cleaned$BMI > 30, na.rm = TRUE)
percent_obese <- (n_obese / nrow(trauma_data_cleaned)) * 100

# Выводим результат
cat("Средний ИМТ:", round(mean_bmi, 2), "(", round(sd_bmi, 2), ")\n")
cat("Доля пациентов с ожирением:", round(percent_obese, 1), "%\n")

```


```{r}

trauma_data_cleaned %>% 
    select(Sex,
           Age,
           Height,
           Weight,
           BMI,
           SBP,
           DBP,
           FOUR,
           GSC,
           Hb,
           Death) %>% 
    tbl_summary(by = Death) 
```

```{r}

roc_curve_1 <- roc(Death ~ Hb, 
                   data = trauma_data_cleaned,
                   ci = T)

roc_curve_1


```

```{r, fig.height=3, fig.width=3, dpi=300}

roc_curve_1 %>% 
    ggroc() + 
    theme_bw()

# Рассчет AUC
auc(roc_curve_1)

# Вывод 95% ДИ для AUC
ci(roc_curve_1)
```

```{r}
roc_curve_1 %>% coords()
```

```{r}
roc_curve_1 %>% coords(x = "best", best.method = "closest.topleft") 
```

```{r}

roc_curve_2 <- roc(Death ~ GSC, 
                   data = trauma_data_cleaned,
                   ci = T)

roc_curve_2
```

```{r, fig.height=3, fig.width=3, dpi=300}

roc_curve_2 %>% 
    ggroc() + 
    theme_bw()

# Рассчет AUC
auc(roc_curve_2)

# Вывод 95% ДИ для AUC
ci(roc_curve_2)

```

```{r}
roc_curve_2 %>% coords()
```

```{r}
roc_curve_2 %>% coords(x = "best", best.method = "closest.topleft") 
```

```{r}
trauma_data_cleaned %>% names()

trauma_data_cleaned %>% 
    
    select("Death",
           "Age",
           "Height",
           "Weight",
           "BMI",
           "SBP",
           "DBP",
           "FOUR",
           "GSC",
           "Hb"
           ) %>% 
    
    pivot_longer(cols = !Death) %>% 
    
    group_by(name) %>% 
    
    summarise(AUC = roc(Death, value, ci = T)$ci[2] %>% round(3),
              AUC_LCL = roc(Death, value, ci = T)$ci[1] %>% round(3),
              AUC_UCL = roc(Death, value, ci = T)$ci[3] %>% round(3))
```

